# Generated by Django 2.0.8 on 2019-03-17 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_post', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(blank=True)),
                ('status_of_post', models.CharField(blank=True, choices=[('nv', 'not verified'), ('v', 'verified'), ('s', 'solved')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('alloted_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('mobile_no', models.CharField(blank=True, max_length=10)),
                ('constituency', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='votes_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.post')),
                ('user_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.Profile'),
        ),
        migrations.AddField(
            model_name='photos',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.post'),
        ),
    ]
