# Generated by Django 2.0.8 on 2019-04-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialissue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='problem_statement',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='weightage',
            field=models.IntegerField(default=0),
        ),
    ]
