# Generated by Django 2.0.8 on 2019-04-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialissue', '0002_auto_20190419_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='file_data',
        ),
    ]
