# Generated by Django 2.0.8 on 2019-04-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialissue', '0008_auto_20190419_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='constituency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status_of_post',
            field=models.CharField(blank=True, choices=[('nv', 'not verified'), ('v', 'verified'), ('s', 'solved'), ('r', 'rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='votes_comments',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.Post'),
        ),
    ]
