# Generated by Django 2.0.8 on 2019-04-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialissue', '0009_auto_20190419_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='only_votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upordown', models.CharField(blank=True, choices=[('u', 'upvote'), ('d', 'downvote')], max_length=10)),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.Post')),
                ('user_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='photos',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.Post'),
        ),
        migrations.AlterField(
            model_name='votes_comments',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.Post'),
        ),
    ]
