# Generated by Django 2.0.8 on 2019-04-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialissue', '0010_auto_20190422_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='only_votes',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.Post'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.Post'),
        ),
        migrations.AlterField(
            model_name='votes_comments',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialissue.Post'),
        ),
    ]
